import = [
  "~/dotfiles/alacritty/themes/gruvbox_material_medium_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 2

decorations = "none"

[window.dimensions]
columns = 140
lines = 35

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12
