console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
terminal_background = 'p:thm_bg'
version = 3
final_space = true

[palette]
  thm_bg = '#282828'
  thm_fg = '#ebdbb2'
  thm_cyan = '#8ec07c'
  thm_black = '#665c54'
  thm_gray = '#928374'
  thm_magenta = '#d3869b'
  thm_pink = '#fb4934'
  thm_red = '#cc241d'
  thm_green = '#b8bb26'
  thm_yellow = '#fabd2f'
  thm_blue = '#83a598'
  thm_orange = '#fe8019'
  thm_black4 = '#3c3836'

[secondary_prompt]
  foreground = 'p:thm_cyan'
  background = 'transparent'

[transient_prompt]
  template = '󱚢  '
  foreground = 'p:thm_orange'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:thm_fg'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

[[blocks.segments]]
    template = '<p:thm_blue> : </><p:thm_cyan>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <p:thm_yellow> {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} | {{ end }}{{ if .Staging.Changed }}<p:thm_blue> {{ .Staging.String }}</>{{ end }} '
    foreground = 'p:thm_fg'
    # background = '#FFFB38'
    type = 'git'
    style = 'powerline'
    # background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}', '{{ if gt .Ahead 0 }}#C792EA{{ end }}', '{{ if gt .Behind 0 }}#C792EA{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = ' '
    foreground = 'p:thm_red'
    type = 'status'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:thm_green'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:thm_blue'
    type = 'php'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Full }}'
    foreground = 'p:thm_yellow'
    type = 'python'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Full }}'
    foreground = 'p:thm_magenta'
    type = 'julia'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Full}}'
    foreground = 'p:thm_red'
    type = 'ruby'
    style = 'plain'

  [[blocks.segments]]
    template = 'ﳑ {{ .Full}}'
    foreground = 'p:thm_cyan'
    type = 'go'
    style = 'plain'

  [[blocks.segments]]
    type = 'react'
    style = 'plain'
    foreground = 'p:thm_orange'
    template = '  {{ .Full }} '

  [[blocks.segments]]
    foreground = 'p:thm_fg'
    type = 'command'
    style = 'plain'

    [blocks.segments.properties]
      command = 'git log --pretty=format:%cr -1'
      shell = 'bash'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '󰫣'
    foreground = 'p:thm_green'
    type = 'text'
    style = 'plain'
